### ISSUE TITLE
Test Case: Tests for Advanced Search Form Trial Investigators Section

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform-qa#178]
# Test URL: 
https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/advanced
# Tests Covered:
- [x] 58.Verify that the 'Trial Investigators ' section is displayed. (#94 )
- [x] 59.Verify that the title 'Trial Investigators' is displayed correctly. (#94 )
- [x] 60. Verify that the 'Trial Investigators' input box help icon links to  https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/help#trialinvestigators (#94 )
- [x] 61.Verify that the placeholder text "Investigator name" appears in the 'Trial Investigators' input box. (#94 )
- [x] 62.Verify that the helper text "Search by trial investigator." appears in the 'Trial Investigators' input box. (#94 )
- [x] 63. Verify that on entering invalid entries to 'Trial Investigators' input box, the error message "No results found" is displayed in place of helper text.

- [x] 61.Verify that the helper text 'Please enter 3 or more characters' appears on clicking the 'Trial Investigators' input box. (#95 )
- [x] 62.Verify that when user selects an option from the autocomplete for the  'Trial Investigators' input box and clicks Find Trials button, correct results are displayed. (#95 )
- [x] 63. Verify that on entering invalid entries to 'Trial Investigators' input box and clicking the submit button, user is directed to No Results page.
- [x] 63. Verify that when user selects an option from the autocomplete for the  'Trial Investigators' input box and hits 'Enter', correct results are displayed.(#95 )

Depends on Issue 
#94 
#95

**Comment by kate-mashkina** [comment]
PR #180 covered this issue
