### ISSUE TITLE
Test Case: Tests for Advanced Search Form Lead Organization Section 

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform-qa#185]
# Test URL: 
https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/advanced
# Tests Covered:
- [x] 63.Verify that the 'Lead Organization' section is displayed. (#94 )
- [x] 64.Verify that the title "Lead Organization " is displayed correctly. (#94 )
- [x] 65.Verify that the 'Lead Organization'  help icon links to  https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/help#leadorganization (#94 )
- [x] 66.Verify that the placeholder text "Organization name" appears in the  'Lead Organization' input box. (#94 )
- [x] 67.Verify that the helper text "Search by lead organization." appears in the  'Lead Organization' input box. (#94 )
- [x] 68. Verify that on entering invalid entries to Lead Organization input box, the error message "No results found" is displayed in place of helper text. 

- [x] 63.Verify that the helper text 'Please enter 3 or more characters' appears on clicking the 'Lead Organization' input box. (#95 )
- [x] 64.Verify that when user selects an option from the autocomplete for the 'Lead Organization' input box and clicks Find Trials button, correct results are displayed. (#95 )
- [x] 65. Verify that when user selects an option from the autocomplete for the 'Lead Organization' input box and hits "Enter", correct results are displayed. (#95 )
- [x] 66. Verify that on entering invalid entries to 'Lead Organization' input box and clicking the submit button, user is directed to No Results page.

Depends on (#94 ) and (#95 )
