### ISSUE TITLE
Test Case: Tests for Advanced Search Form Trial Phase Section

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform-qa#188]
# Test URL: 
https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/advanced
# Tests Covered:
- [x] 48.Verify that the'Trial Phase' section is displayed. (#94 )
- [x] 53. Verify that the check box "All" is selected by default for the 'Trial Phase' section. (#94 )
- [x] 55.Verify that when any one checkbox is selected for the Trial Phase , 'All' checkbox gets deselected. (#95 )
 - [x] 56.Verify that when none of the checkbox is selected for the Trial Phase,'All' checkbox gets selected. (#95 )
 - [x] 56. Verify when the user selects the 'All' check box for the Trial Phase and clicks Find Trials button, correct results are displayed. (#95 )
 - [x] 57.Verify that when the user selects one of the checkbox (e.g. Phase I) for the Trial Phase and clicks Find Trials button, correct results are displayed. (#95 )
- [x] 58.Verify that when the user selects more than one checkbox (e.g. Phase I and Phase II checkbox) in the the Trial Phase  section and clicks Find Trials button, correct results are displayed. (#95 )

Depends on Issue #94 and #95

**Comment by kate-mashkina** [comment]
PR#191 closed this issue
