### ISSUE TITLE
Test Case: Tests for Advanced Search Form Trial Type Section 

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform-qa#190]
# Test URL: 
https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/advanced
# Tests Covered:
- [x] 30.Verify that the 'Trial Type' section is displayed. (#94 )
- [x] 44. When the user switches the healthy volunteer toggle first to 'YES' and then  to "NO" in the Trial Type section and clicks Find Trials button, we will verify that system goes back to displaying default (not filtered by healthy volunteers) results after search submitted. (#95 )
- [x] 44. Verify when the toggle is switched to 'Yes' and Find  Find Trials button, is clicked correct results are displayed. (#95 )
- [x] 37.Verify that the checkbox "All" is selected by default for the 'Trial Type'  input box. (#94 )
- [x] 45. Verify that when 'All' checkbox is selected and user clicks Find Trials button, all results are displayed. (#95 )
- [x] 45.Verify that when any one checkbox is selected for the Trial Type ,  'All' checkbox gets deselected. (#95 )
- [x] 45.Verify that when none of the checkbox is selected for the Trial Type,'All' checkbox gets selected. (#95 )
- [x] 46.Verify that when the user selects any one checkbox (e.g. Treatment) for the Trial Type and clicks Find Trials button, correct results are displayed. (#95 )
- [x] 48. Verify that when the user selects more than one checkbox (e.g. Treatment and Prevention) for the Trial Type and clicks Find Trials button, correct results are displayed. (#95 )
Depends on Issue #<number> (#94 ) and (#95 )

**Comment by kate-mashkina** [comment]
PR #211 is merged
