### ISSUE TITLE
Test Case: Verify Citations

### ISSUE THREAD

**Issue by popkhadzeg** [NCIOCPL/cgov-digital-platform-qa#21]
# Pre-requisites
* Content Type Article, Press Release, Blog, PDQ CIS have been migrated.

# Content Types Covered
- [ ] [Article](https://github.com/NCIOCPL/cgov-digital-platform/issues/889)
[](url)
- [ ] [Press Release](NCIOCPL/cgov-digital-platform#891)
- [ ] [Blog](NCIOCPL/cgov-digital-platform#890)
- [ ] PDQ  CIS - (will be tested in #76)
 
# Test scenarios for Citations:

1.Navigate to page URL for each content type
2.Verify that the Citation Section is present
3.Verify that the Citation Header is visible
4.Verify that the Citation Text is correct 
5.Verify that the Citation Text length is correct (within a specified range) for each Citation
6.Verify that the Pub Med link Exists for Citations
7.Verify that the PubMed link point to PubMed URL

Negative Tests for Citations:
1. Navigate to other content type pages (except Article, Press Release, Blog Posts) and verify Citation Section doesn't appear.
2. Verify that Pub Med links does not appear in citations where it is not expected to appear.
