### ISSUE TITLE
Remove ' verifyPagesWithBrowserTitle' test from metaData.MetaData_Test

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform-qa#220]
Remove ' verifyPagesWithBrowserTitle' test

This test verifies the presence of a meta tag in the form `<meta name="title" content="The title of the page" />`.  This tag only existed because of [a bug in the Drupal metatag module](https://www.drupal.org/node/3099168) and now that the bug has been resolved, this test fails.

### Sub-Tasks
- [x] Remove the `verifyPagesWithBrowserTitle` method from `src/test/java/gov/cancer/tests/metaData/MetaData_Test.java`
- [x] Remove the `getMetaTitle` method from `src/main/java/gov/cancer/pageobject/crosscutting/PageWithMetaData.java`
- [x] Remove the  `metaTitle` selector from `src/main/java/gov/cancer/pageobject/crosscutting/PageWithMetaData.java`
