### ISSUE TITLE
Create Test Plan

### ISSUE THREAD

**Issue by amydugan** [NCIOCPL/cgov-digital-platform-qa#25]
## 1. Introduction
This document records the detailed test plan for the quality assurance effort necessary to validate the final functionality of CancerGov Digital Platform migration to Drupal CMS.

## 2. Test Approach
The Test Approach presents the overall strategy for verifying the requirements to be tested.  

## 3. Test Objectives
The major testing objectives are: 
•	Functional Testing to ensure that the CancerGov Digital Platform is developed as per the scope captured in respective User Stories,  Annotated Wireframes
•	Define the test cases for the stories within that iteration
•	Test the stories being implemented during that iteration 
•	Test Scripts preparation for automation regression testing

## 4. YAML Content Request for:

- [x] Related Resources - Blog #864
- [x] Related Resources - Press Release #866 
- [x] Related Resources - Article #867
- [x] Related Resources - Cancer Center #868 
- [x] Related Resources - Biography #869 
- [x] Posted Date- Blog #872
- [x] Reviewed Date - Article #873 
- [x] Updated Date - Press Release #875
- [x] Updated Date - Cancer Center #876 
- [x] Lead Image - Article #879 
- [ ] Lead Image - Blog #880 
- [ ] Syndicate - Article #881 
- [ ] Public Use - Article #883 
- [x] Intro Text - Article #885 
- [x] Intro Text - Blog #886 
- [ ] Citations - Article #889 
- [ ] Citations -  Blog #890 
- [ ] Citations -  Press Release #891 
- [ ] Recommended Content -  Blog #892

## 5. Test Case Scenarios
**Verify Cross-Cutting Elements on pages:** 
- [ ] Verify Cross-Cutting Elements #894

**Verify common UI elements on content type pages:** 
- [x] Test Case: Verify Browser Title https://github.com/NCIOCPL/cgov-digital-platform-qa/issues/13
- [x] Test Case: Verify Posted Date #871
- [x] Test Case: Verify Reviewed Date #874
- [x] Test Case: Verify Updated Date #877
- [ ] Test Case: Verify Lead Image #878 
- [ ] Test Case: Verify Syndicate #882 
- [ ] Test Case: Verify Public Use #884
- [ ] Test Case: Verify Intro Text #887
- [ ] Test Case: Verify Citations #888
- [x] Test Case: Verify Related Resources #865
- [ ] Test Case: Verify Recommended Content https://github.com/NCIOCPL/cgov-digital-platform-qa/issues/22

## 6. Bugs
- [ ]  - Intro Text styling on Article/Blog pages #843
- [x] - Footer class and the child div tag are appearing twice #1376
- [ ] - Public Use text should reference the content title on Blog Post page #1507
