### ISSUE TITLE
Test Case: Verify Basic Clinical Trial Search Form

### ISSUE THREAD

**Issue by SupriyaSaxena0605** [NCIOCPL/cgov-digital-platform-qa#91]
# Pre-requisites
* pre-condition

# Content Types Covered:
https://www.cancer.gov/about-cancer/treatment/clinical-trials/search

# Test scenarios:
- [x] 3. Verify that the Cancer Type/ Keyword input box is displayed correctly. [#2359](https://github.com/NCIOCPL/cgov-digital-platform/issues/2359)
- [x] 4.  Verify that the title 'Cancer Type/ Keyword' is displayed for Cancer Type/ Keyword input box. [#2359](https://github.com/NCIOCPL/cgov-digital-platform/issues/2359)
- [x] 5. Verify that the Cancer Type/ Keyword input box displays help icon and link (https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/help#basicsearch). [#2359](https://github.com/NCIOCPL/cgov-digital-platform/issues/2359)
- [x] 6. Verify that the Cancer Type/ Keyword input box is displayed correctly with placeholder text "Start typing to select a cancer type or keyword".[#2359](https://github.com/NCIOCPL/cgov-digital-platform/issues/2359)
- [x] 7. Verify that the 'Age' input box is displayed correctly. [#2361](https://github.com/NCIOCPL/cgov-digital-platform/issues/2361)
- [x] 8. Verify that the correct label for the 'Age' input box is displayed. [#2361](https://github.com/NCIOCPL/cgov-digital-platform/issues/2361)
- [x] 9. Verify that the 'Age' input box displays help icon and link (https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/help#basicsearch) [#2361](https://github.com/NCIOCPL/cgov-digital-platform/issues/2361)
- [x] 10. Verify that the 'Age' input box displays help text input as"Your age helps determine which trials are right for you."[#2361](https://github.com/NCIOCPL/cgov-digital-platform/issues/2361)
- [x] 11. Verify that the 'U.S.ZIP Code' input box is displayed correctly. [#2360](https://github.com/NCIOCPL/cgov-digital-platform/issues/2360)
- [x] 12. Verify that the 'U.S.ZIP Code' input box label is displayed correctly.[#2360](https://github.com/NCIOCPL/cgov-digital-platform/issues/2360)
- [x] 13. Verify that the 'U.S.ZIP Code' input box displays help icon and link (https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/help#basicsearch) [#2360](https://github.com/NCIOCPL/cgov-digital-platform/issues/2360)
- [x] 14. Verify that the 'U.S.ZIP Code' input box is displays help text as "Show trials near this U.S. ZIP code." [#2360](https://github.com/NCIOCPL/cgov-digital-platform/issues/2360)
- [x] 15. Verify that the button 'Find Trials' is displayed correctly and label is correct.

Depends on Issue [#2390](https://github.com/NCIOCPL/cgov-digital-platform/issues/2390)
Related Tests: #99  #105 #101

**Comment by SupriyaSaxena0605** [comment]
Assigning to Victoria for test case review

**Comment by VictoriaSunNIH** [comment]
@SupriyaSaxena0605 - I need to check on #10 and #14, because I think we standardized the text.  Will get back to you.

**Comment by SupriyaSaxena0605** [comment]
Updated test# 6 for the text as 'Start typing to select a cancer type or keyword'

**Comment by VictoriaSunNIH** [comment]
Looks good.
